### ISSUE TITLE
Publish new release and setup CI

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher.JsonRPC.Python#10]
changes made so need to publish new release and setup CI

**Comment by Zeroto521** [comment]
Sorry for the late reply. I get some leisure time to do this now.

I need your help, set two action secrets would send an email to you.

**Comment by Zeroto521** [comment]
Three steps to release when features are already.

1. update version
2. build
3. publish to where
    1. github release
    2. pypi

**Comment by jjw24** [comment]
> Sorry for the late reply. I get some leisure time to do this now.
> 
> I need your help, set two action secrets would send an email to you.

added
