### ISSUE TITLE
[Help wanted] add project link

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher.JsonRPC.Python#6]
We need to add a link to the PyPI page.

The link is https://pypi.org/project/flowlauncher.

**Comment by jjw24** [comment]
Add this link to the python template project?

**Comment by Zeroto521** [comment]
In general python package will add a link to PyPI or doc home page.

A link to the python plugin template project may is another decision.

**Comment by jjw24** [comment]
done
